import { CrawlResult, CrawledPage, CrawledForm, CrawledFormField, InteractiveElement } from './siteCrawler.js';
import { BrowserStep, BrowserTestSpec } from './types.js';
import { ParsedCaseDraft } from './specParser.js';

let stepCounter = 0;
function nextStepId(): string {
  stepCounter += 1;
  return `step_${stepCounter}_${Date.now().toString(36)}`;
}

const NAMED_FIELD_RECOGNIZERS: Array<{ pattern: RegExp; value: string }> = [
  { pattern: /\bfirst.?name\b|\bgiven.?name\b/i, value: 'Jordan' },
  { pattern: /\blast.?name\b|\bsurname\b|\bfamily.?name\b/i, value: 'Rivera' },
  { pattern: /\bfull.?name\b|^name$|\byour.?name\b/i, value: 'Jordan Rivera' },
  { pattern: /\buser.?name\b/i, value: 'verity_qa_test' },
  { pattern: /\bcompany\b|\borgani[sz]ation\b|\bemployer\b/i, value: 'Verity QA Testing Co.' },
  { pattern: /\bjob.?title\b|\bposition\b|\brole\b/i, value: 'QA Engineer' },
  { pattern: /\baddress.?line.?1\b|\bstreet\b|\baddress\b(?!.?line.?2)/i, value: '123 Test Street' },
  { pattern: /\baddress.?line.?2\b|\bapt\b|\bsuite\b|\bunit\b/i, value: 'Suite 4' },
  { pattern: /\bcity\b|\btown\b/i, value: 'Springfield' },
  { pattern: /\bstate\b|\bprovince\b|\bregion\b(?!ex)/i, value: 'CA' },
  { pattern: /\bzip\b|\bpostal\b|\bpostcode\b/i, value: '94105' },
  { pattern: /\bcountry\b/i, value: 'United States' },
  { pattern: /\bage\b/i, value: '29' },
  { pattern: /\bsubject\b|\btopic\b/i, value: 'QA Automation Test Inquiry' },
  { pattern: /\bmessage\b|\bcomment(s)?\b|\bfeedback\b|\bdescription\b|\bnotes?\b/i, value: 'This is an automated QA test submission generated by Verity. Please disregard.' },
  { pattern: /\bbirth.?place\b/i, value: 'Springfield' },
  { pattern: /\bquantity\b|\bqty\b/i, value: '1' },
  { pattern: /\bcoupon\b|\bpromo.?code\b|\bdiscount.?code\b/i, value: 'TESTCODE' },
];

export function generateFieldValue(field: CrawledFormField): { value: string; needsUserInput: boolean } {
  const placeholderRef = `{{${field.name}}}`;

  if (field.sensitive) {
    return { value: placeholderRef, needsUserInput: true };
  }

  const signal = `${field.name} ${field.label || ''} ${field.placeholder || ''}`.replace(/[_-]/g, ' ');

  if (/\b(id|number|reference|order|account|ssn|passport|license|tracking)\b/i.test(signal)) {
    return { value: placeholderRef, needsUserInput: true };
  }

  for (const recognizer of NAMED_FIELD_RECOGNIZERS) {
    if (recognizer.pattern.test(signal)) {
      return { value: recognizer.value, needsUserInput: false };
    }
  }

  switch (field.type) {
    case 'email':
      return { value: 'qa.automation.test@example.com', needsUserInput: false };
    case 'tel':
      return { value: '+1 555 0100', needsUserInput: false };
    case 'url':
      return { value: 'https://example.com', needsUserInput: false };
    case 'number':
    case 'range':
      return { value: '1', needsUserInput: false };
    case 'date':
      return { value: new Date().toISOString().slice(0, 10), needsUserInput: false };
    case 'checkbox':
      return { value: 'true', needsUserInput: false };
    case 'select':
      if (field.options && field.options.length > 0) {
        return { value: field.options[0], needsUserInput: false };
      }
      return { value: placeholderRef, needsUserInput: true };
    case 'search':
    case 'text':
    case 'textarea':
      return { value: `Verity QA Test — ${field.name}`, needsUserInput: false };
    default:
      return { value: placeholderRef, needsUserInput: true };
  }
}

function buildFormTestSteps(page: CrawledPage, form: CrawledForm): { steps: BrowserStep[]; requiresUserSuppliedData: string[] } {
  const steps: BrowserStep[] = [];
  const requiresUserSuppliedData: string[] = [];

  steps.push({
    id: nextStepId(),
    action: 'navigate',
    url: page.url,
    description: `Navigate to ${page.url}`,
  });

  // Scope every selector below to THIS specific form, not just any form on
  // the page. A page can have multiple forms (a real, common case — e.g.
  // pypi.org has both a search form and a separate locale-switcher form),
  // and an unscoped selector like 'form button[type="submit"]' matches the
  // FIRST such element in document order, which may belong to a different,
  // unrelated form entirely. Caught via genuine Playwright execution
  // against a real multi-form page, not a hypothetical: the generic
  // selector clicked pypi.org's hidden locale-switcher "Deutsch" button
  // instead of the search form's own submit button, timing out because
  // that element was never visible. Scoping by one of the form's own known
  // field names (guaranteed to exist — callers already skip zero-field
  // forms) via Playwright's :has() selector fixes this regardless of form
  // nesting/position on the page.
  const formScope = `form:has([name="${form.fields[0].name}"])`;

  for (const field of form.fields) {
    const { value, needsUserInput } = generateFieldValue(field);
    if (needsUserInput) requiresUserSuppliedData.push(field.name);

    const selector = `${formScope} [name="${field.name}"]`;
    const fieldLabel = field.label || field.name;
    if (field.type === 'select') {
      steps.push({ id: nextStepId(), action: 'select', selector, value, description: `Select "${value}" in ${fieldLabel}` });
    } else if (field.type === 'checkbox') {
      steps.push({ id: nextStepId(), action: 'check', selector, description: `Check ${fieldLabel}` });
    } else {
      steps.push({ id: nextStepId(), action: 'fill', selector, value, description: `Fill ${fieldLabel}` });
    }
  }

  steps.push({
    id: nextStepId(),
    action: 'click',
    selector: `${formScope} button[type="submit"], ${formScope} input[type="submit"]`,
    description: 'Submit the form',
    continueOnFailure: false,
  });

  steps.push({
    id: nextStepId(),
    action: 'assertNoConsoleErrors',
    description: 'Confirm the page produced no JavaScript console errors during this flow',
    continueOnFailure: true,
  });

  return { steps, requiresUserSuppliedData };
}

function buildPageHealthSteps(page: CrawledPage): BrowserStep[] {
  return [
    { id: nextStepId(), action: 'navigate', url: page.url, description: `Navigate to ${page.url}` },
    { id: nextStepId(), action: 'assertUrl', value: page.url, description: 'Confirm the page did not redirect unexpectedly' },
    { id: nextStepId(), action: 'assertNoConsoleErrors', description: 'Confirm no JavaScript console errors on load', continueOnFailure: true },
    { id: nextStepId(), action: 'assertNoBrokenLinks', description: 'Confirm every same-origin link on this page resolves without a 4xx/5xx response', continueOnFailure: true },
  ];
}

function describeKind(kind: InteractiveElement['kind']): string {
  switch (kind) {
    case 'button': return 'button';
    case 'js_anchor': return 'JS-driven link';
    case 'onclick_handler': return 'onclick element';
    case 'aria_control': return 'ARIA control';
    case 'disclosure': return 'disclosure widget';
  }
}

function buildInteractiveElementSteps(page: CrawledPage): BrowserStep[] | null {
  if (page.interactiveElements.length === 0) return null;

  const steps: BrowserStep[] = [
    { id: nextStepId(), action: 'navigate', url: page.url, description: `Navigate to ${page.url}` },
  ];

  for (const el of page.interactiveElements.slice(0, 15)) {
    steps.push({
      id: nextStepId(),
      action: 'click',
      selector: el.selector,
      description: `Click "${el.text}" (${describeKind(el.kind)})`,
      continueOnFailure: true,
    });
  }

  steps.push({
    id: nextStepId(),
    action: 'assertNoConsoleErrors',
    description: 'Confirm none of the above interactions produced a JavaScript console error',
    continueOnFailure: true,
  });

  return steps;
}

/**
 * Turns a crawl result into a set of real, executable browser test case
 * drafts — one page-health check per crawled page, plus one form-fill-and-
 * submit test per discovered form. Every draft's dataFields lists exactly
 * the fields a human needs to supply (via the dataset configurator) before
 * the test can run meaningfully; nothing sensitive is ever auto-filled.
 */
export function generateBrowserTestDrafts(crawl: CrawlResult): ParsedCaseDraft[] {
  const drafts: ParsedCaseDraft[] = [];

  for (const page of crawl.pages) {
    if (page.error || page.status === null) continue;

    const pagePath = (() => {
      try {
        const u = new URL(page.url);
        return u.pathname === '/' ? 'Home' : u.pathname;
      } catch {
        return page.url;
      }
    })();

    const healthSpec: BrowserTestSpec = { startPath: page.url, steps: buildPageHealthSteps(page) };
    drafts.push({
      ext_id: `browser_health_${drafts.length + 1}`,
      title: `${pagePath} — loads cleanly with no console errors or broken links`.slice(0, 140),
      category: 'Browser / Page Health',
      priority: page.url === crawl.rootUrl ? 'High' : 'Medium',
      tags: 'browser,page-health,auto-generated',
      type: 'browser',
      spec: { browser: healthSpec },
      dataFields: [],
    });

    for (const [formIdx, form] of page.forms.entries()) {
      if (form.fields.length === 0) continue;
      const { steps, requiresUserSuppliedData } = buildFormTestSteps(page, form);
      const formSpec: BrowserTestSpec = { startPath: page.url, steps, requiresUserSuppliedData };
      const fieldLabels = form.fields.map(f => f.label || f.name).slice(0, 3).join(', ');
      drafts.push({
        ext_id: `browser_form_${drafts.length + 1}`,
        title: `${pagePath} — form #${formIdx + 1} (${fieldLabels}${form.fields.length > 3 ? ', …' : ''}) can be filled and submitted`.slice(0, 140),
        category: 'Browser / Form Submission',
        priority: requiresUserSuppliedData.length > 0 ? 'Medium' : 'High',
        tags: `browser,form${requiresUserSuppliedData.length > 0 ? ',needs-test-data' : ''},auto-generated`,
        type: 'browser',
        spec: { browser: formSpec },
        dataFields: requiresUserSuppliedData,
      });
    }

    const interactiveSteps = buildInteractiveElementSteps(page);
    if (interactiveSteps) {
      const controlCount = page.interactiveElements.length;
      const interactiveSpec: BrowserTestSpec = { startPath: page.url, steps: interactiveSteps };
      drafts.push({
        ext_id: `browser_controls_${drafts.length + 1}`,
        title: `${pagePath} — ${controlCount} interactive control${controlCount === 1 ? '' : 's'} respond without errors`.slice(0, 140),
        category: 'Browser / Interactive Controls',
        priority: 'Medium',
        tags: 'browser,interactive-controls,auto-generated',
        type: 'browser',
        spec: { browser: interactiveSpec },
        dataFields: [],
      });
    }
  }

  return drafts;
}
