import React from 'react';
import {
  Shield,
  Lock,
  CheckCircle2,
  Sparkles,
  Server,
  Key,
  FileCheck,
  Building,
  ArrowRight,
  Globe2,
} from 'lucide-react';

interface AboutViewProps {
  onStartStudio: () => void;
  onOpenContact: () => void;
}

export const AboutView: React.FC<AboutViewProps> = ({ onStartStudio, onOpenContact }) => {
  return (
    <div className="relative min-h-screen bg-[#07080D] text-slate-100 py-12 px-4 sm:px-6 lg:px-8">
      {/* Background ambient */}
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="absolute -top-40 left-1/4 w-[700px] h-[350px] bg-emerald-500/10 blur-[140px] rounded-full" />
        <div className="absolute top-1/3 -left-40 w-[450px] h-[450px] bg-teal-500/10 blur-[150px] rounded-full" />
      </div>

      <div className="relative mx-auto max-w-7xl">
        {/* Breadcrumb Navigation for SEO */}
        <nav aria-label="Breadcrumb" className="mb-6 flex items-center gap-2 text-xs text-slate-400">
          <a href="#home" className="hover:text-emerald-400 transition">Verity QA Platform</a>
          <span>/</span>
          <span className="text-emerald-400 font-semibold">About & Security Architecture</span>
        </nav>

        {/* Header Hero */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center gap-2 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-3 py-1 text-xs font-semibold text-emerald-300 mb-4">
            <Shield className="h-3.5 w-3.5 text-emerald-400" />
            <span>Mission & Zero-Trust Governance</span>
          </div>
          <h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight text-white mb-4">
            Building the Standard for <span className="text-emerald-400">Authentic QA Automation</span>
          </h1>
          <p className="text-sm sm:text-base text-slate-300 leading-relaxed">
            Software teams are constantly slowed down by flaky tests written against imaginary dummy data. Verity was created to unify real-time network introspection, zero dummy data datasets, and self-contained Docker packaging.
          </p>
        </div>

        {/* Core Pillars */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
          <div className="rounded-2xl border border-[#1E2235] bg-[#0C0E17]/90 p-6 sm:p-8 shadow-xl">
            <div className="h-10 w-10 rounded-xl bg-emerald-500/10 flex items-center justify-center text-emerald-400 border border-emerald-500/20 mb-4">
              <Server className="h-5 w-5" />
            </div>
            <h2 className="text-lg font-bold text-white mb-2">Zero Dummy Data Guarantee</h2>
            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
              Every route, query parameter, and assertion in a Verity suite originates from real-world network probes or developer-confirmed specifications. We reject synthetic hallucinations that break when exposed to live APIs.
            </p>
          </div>

          <div className="rounded-2xl border border-[#1E2235] bg-[#0C0E17]/90 p-6 sm:p-8 shadow-xl">
            <div className="h-10 w-10 rounded-xl bg-teal-500/10 flex items-center justify-center text-teal-400 border border-teal-500/20 mb-4">
              <Key className="h-5 w-5" />
            </div>
            <h2 className="text-lg font-bold text-white mb-2">Zero-Trust Credential Isolation</h2>
            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
              Sensitive authentication tokens, Bearer secrets, and API credentials are protected with end-to-end token masking. Credentials are never written to exported package code or committed to public version control.
            </p>
          </div>

          <div className="rounded-2xl border border-[#1E2235] bg-[#0C0E17]/90 p-6 sm:p-8 shadow-xl">
            <div className="h-10 w-10 rounded-xl bg-cyan-500/10 flex items-center justify-center text-cyan-400 border border-cyan-500/20 mb-4">
              <Globe2 className="h-5 w-5" />
            </div>
            <h2 className="text-lg font-bold text-white mb-2">Multi-Cloud Freedom</h2>
            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
              No vendor lock-in. Every test suite generated by Verity can be exported as a standard, self-contained Docker bundle and executed across AWS, GCP, Azure, Kubernetes, or air-gapped private networks for $0.
            </p>
          </div>
        </div>

        {/* Security & Compliance Section */}
        <div className="rounded-2xl border border-[#1E2235] bg-[#0C0E17]/90 p-6 sm:p-8 shadow-xl mb-16">
          <div className="mb-6">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <Lock className="h-5 w-5 text-emerald-400" />
              <span>Enterprise Security, Privacy & Compliance</span>
            </h2>
            <p className="text-xs text-slate-400 mt-1">
              Verity adheres to enterprise-grade compliance frameworks and data protection standards.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 text-xs">
            <div className="rounded-xl border border-[#1E2235] bg-[#06070B] p-4">
              <div className="flex items-center gap-2 text-emerald-400 font-bold mb-1">
                <FileCheck className="h-4 w-4" />
                <span>SOC 2 Type II Ready</span>
              </div>
              <p className="text-slate-400 text-[11px] leading-relaxed">
                Segregated tenant environments, audited access controls, and TLS 1.3 in transit.
              </p>
            </div>

            <div className="rounded-xl border border-[#1E2235] bg-[#06070B] p-4">
              <div className="flex items-center gap-2 text-emerald-400 font-bold mb-1">
                <FileCheck className="h-4 w-4" />
                <span>GDPR & CCPA Compliant</span>
              </div>
              <p className="text-slate-400 text-[11px] leading-relaxed">
                Full user data deletion rights, zero unauthorized tracking, and strict consent handling.
              </p>
            </div>

            <div className="rounded-xl border border-[#1E2235] bg-[#06070B] p-4">
              <div className="flex items-center gap-2 text-emerald-400 font-bold mb-1">
                <FileCheck className="h-4 w-4" />
                <span>Immutable Audit Trails</span>
              </div>
              <p className="text-slate-400 text-[11px] leading-relaxed">
                Every test execution, credit allocation, and role change is permanently logged.
              </p>
            </div>

            <div className="rounded-xl border border-[#1E2235] bg-[#06070B] p-4">
              <div className="flex items-center gap-2 text-emerald-400 font-bold mb-1">
                <FileCheck className="h-4 w-4" />
                <span>Air-Gapped Execution</span>
              </div>
              <p className="text-slate-400 text-[11px] leading-relaxed">
                Standalone Docker bundles can run completely offline without external internet calls.
              </p>
            </div>
          </div>
        </div>

        {/* CTA Footer */}
        <div className="rounded-2xl border border-emerald-500/40 bg-gradient-to-r from-emerald-500/10 via-teal-500/10 to-transparent p-6 sm:p-8 flex flex-col sm:flex-row items-center justify-between gap-6 shadow-xl">
          <div>
            <h3 className="text-lg font-bold text-white">Partner with Verity Engineering</h3>
            <p className="text-xs text-slate-300 mt-1 max-w-xl">
              Discuss custom VPC deployment, volume credit contracts, or dedicated support SLAs with our team.
            </p>
          </div>
          <div className="flex items-center gap-3 shrink-0">
            <button
              onClick={onOpenContact}
              className="rounded-xl border border-[#1E2235] bg-[#131622] px-4 py-2 text-xs font-semibold text-slate-200 hover:bg-[#1A1D2B] transition"
            >
              Contact Solutions
            </button>
            <button
              onClick={onStartStudio}
              className="flex items-center gap-1.5 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-500 px-4 py-2 text-xs font-bold text-slate-950 shadow-md shadow-emerald-500/20 hover:from-emerald-400 hover:to-teal-400 transition"
            >
              <Sparkles className="h-3.5 w-3.5" />
              <span>Launch Studio Free</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
